name = "Better MC"
author = "mc-infra"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60ed343898ce5ab5a29855fe47035dee41f95013e02e34d47ac5393fec52e503"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
