name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b133b4a487fce75e01e824b26896719f5a11466444acd324c93974f5ad069f5f"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
