name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8d9f8290ad4c133887f27a1e070517235687a08443d4a92eb80ec55ba3ee1233"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
