name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc5341cc03d81278b7a4e4454e41dfa529b4a1dd782fe149f6795a10ff39d1fc"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
