name = "Better MC"
author = "mc-infra"
version = "v2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a217bf1f6f0265dc22c672bcd937c7fe057341bb1b3e142830bcd7c2d08afa9d"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
