name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb337ca771ae116fb9e88eb263cc09f7b4e63453a8470f0388092805b455d665"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
