name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d28217f760df2e3fb6b4ce491102d8918afa4394a85d51b70a592efe11a5b8de"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
