name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78374be4df849342b86b1fa1d62636906c23dbefdbc470a0ee74bd6045e25f6b"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
