name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "48a26b9e1b33c04efa1a8c62a79060188f22a5c1e7817f9947b20dd09985fe8d"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
