name = "Better MC"
author = "mc-infra"
version = "v2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "04f609faa4c57d8108040d2d70beeb0cef6d4ca7393284b35cf1f6f7d63fbc34"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
