name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "12814e4889ab8dbcf018a1bf205bd80b14b45b7a629c4ae4e77a73a577eb1cb3"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
