name = "Better MC"
author = "mc-infra"
version = "v2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "616a0343ca1265a5c56e9d4ffc2a6a3900bdde22c8abc4c57457b4c5bdf0f7a8"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
