name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cc50288221a1d87982c5711c79b7286e815aca4416523a41fda9593a1e50f42"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
