name = "Better MC"
author = "mc-infra"
version = "v2.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a0081063189c29980be6c1331b33836463b3aa9da8b6e0cddfdaad307e5e8d3"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
