name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb7182ac30f53f8ad50ebdbf325c12012f61bb115ad9516a44c6af2b035536da"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
