name = "Better MC"
author = "mc-infra"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ed996471b9f598a0d5303993f86ab47f3bb0e702b00c95f07eadda196d7e605"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
