name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b792fea2ac3c895aa5ed420baa13b26ec5cfd85cc4bb520c1125eb22835cea03"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
