name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2ebbb5fa0eba64e60125cde20f94559bcce84adea439f5c8eed05bc4784094df"

[versions]
fabric = "0.14.7"
minecraft = "1.18.2"
