name = "Better MC"
author = "mc-infra"
version = "v2.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc294c2fd40956d87e2b69451c2230077885cee2601423d842679eb7c321b7b0"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
