name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0efc93a7bbbee59b3c173158bbe6ffa0c8aa416a23a0dc79f493c42d2e7dbadb"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
