name = "Better MC [FABRIC] - v13"
author = "SHXRKlE"
version = "v13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d3b8bb527e7ec64e0deb3c07bd7f63b01e1b7f7a75081fcfeaf4acd447e60d22"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"
