name = "Better MC"
author = "mc-infra"
version = "v2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e26432d9c27af6bdccbcb411e7f4df52e4f5cfec75687cccceb2caa834565e2e"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
