name = "Better MC"
author = "mc-infra"
version = "v2.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b655423dcf2ed81f0226406a8c5814747b5870eab5ea6ed8ea6808514f6c7264"

[versions]
fabric = "0.14.8"
minecraft = "1.19"
